train:
    epochs: 60000
    batch_size: 16
    lr: 0.002
    gamma: 0.99
    sync_rate: 10
    policy:
        eps_last_frame: 1000
        eps_start: 1.0
        eps_end: 0.01

data:
    voc:
        root: "../../Data/VOC/"
        year: "2012"
        image_set: "train"
        download: False
    buffer:
        episode_length: 10
        replay_size: 1000
        warm_start_steps: 10
    transforms:
        voc_transforms:
            _target_: rl.data.transforms.voc_transforms
            image_size: [224, 224]
            hflip: 0.0
            vflip: 0.0
            brightness_contrast: 0.0
        corruption_transforms:
            _target_: rl.data.transforms.corruption_transforms
            scale: 0.3


model:
    backbone:
        _target_: rl.models.backbones.resnet50
    bar:
        c: 0.1
        beta: 0.9
    sift:
        beta: 0.9