train:
    eps: 0.1
    sync_rate: 10
    gamma: 0.99
    policy_learning_rate: 3e-4
    q_learning_rate: 3e-4
    tau: 5e-3
    hidden_size: 500
    batch_size: 16
    replay_size: 2000
    warm_start_size: 100
    avg_reward_len: 100
    min_episode_reward: -300
    batches_per_epoch: 10
    num_workers: 1
    n_steps: 1

env:
    seed: 123
    backbone:
        _target_: sift.networks.backbones.resnet50
    voc_transforms:
        _target_: sift.data.transforms.voc_transforms
        image_size: [224, 224]
        hflip: 0.0
        vflip: 0.0
        brightness_contrast: 0.0
    corruption_transforms:
        _target_: sift.data.transforms.corruption_transforms
        scale: 0.25
        prob: 0.5
    root: "../../Data/VOC/"
    year: "2012"
    image_set: "train"
    download: False
    beta: 0.9
